# Compresión de imágenes usando SVD

### Alberto Márquez
### María Vara
### Darío Sotelo

#### Análisis Aplicado

Importamos las siguientes paqueterías:

In [1]:
import numpy as np
from scipy.linalg import svd
from matplotlib.image import imread
import matplotlib.pyplot as plt
import os

El método es:

In [19]:
def singular_value_descomposition(Mat):
    aux1 = np.dot(Mat, Mat.T)
    
    #Primero vamos a obtener los eigenvalores y eigenvectores de la matriz
    eigval, eigvec = np.linalg.eig(aux1)
    
    
    #En esta línea se ordenan los eigenvalores en orden ascendente con la función argsort()
    #y después se revierte el orden del arreglo con la instrucción [::-1], ahora tenemos una lista de 
    #eigenvalores ordenados de forma descendiente
    eigenval_desc = np.argsort(eigval)[::-1]
    
    
    #En la siguiente línea se le asigna a U el valor de los eigenvectores correspondientes a los eigenvalores
    #de forma descendente.
    U = eigvec[:, eigenval_desc]
    
    
    #La siguiente matriz que vamos a obtener es Vt
    #primero calculamos el producto de Mt*M
    aux2 = np.dot(Mat.T, Mat)
    
    #Se obtienen los eigenvalores y eigenvectores de las matrices multiplicadas
    eigval, eigvec = np.linalg.eig(aux2)
    
    #Se vuelven a ordenar de igual forma que la matriz U
    eigenval_desc = np.argsort(eigval)[::-1]
    
    Vt = eigvec[:, eigenval_desc].T
    
    #Por último tenemos que obtener la matriz sigma, la cual tenemos que descartar un tamaño,
    #es decir, nos vamos a quedar con una matriz cuadrada y tenemos que medir el tamaño de la multiplicación
    mat_calc = np.dot(Mat.T, Mat) if (np.size(np.dot(Mat, Mat.T)) > np.size(np.dot(Mat.T, Mat))) else np.dot(Mat, Mat.T)
    
    #En esta línea se sacan los eigenvalores y eigenvectores de la matriz que resultó ser la "buena" (cambiar esta palabra)
    eigval, eigvec = np.linalg.eig(mat_calc)
    
    #Se le aplica la raíz a los eigenvalores
    eigval = np.sqrt(eigval)
    
    sigma = eigval[::-1]
    
    return U, sigma, Vt

In [20]:
A = np.array([[4,2,0],[1,5,6]])

U, Sigma, Vt = singular_value_descomposition(A)
print("-------------------U-------------------")
print(U)
print("\n--------------Sigma----------------")
print(Sigma)
print("\n-------------V transpose---------------")
print(Vt)
newSigma = np.zeros((2, 3))
newSigma[:2, :2] = np.diag(Sigma[:2])

print(A,"\n")

A_remake = (U @ newSigma @ Vt)
print(A_remake)

-------------------U-------------------
[[-0.28978415 -0.95709203]
 [-0.95709203  0.28978415]]

--------------Sigma----------------
[8.13872588 3.97003036]

-------------V transpose---------------
[[-0.26001965 -0.65919758 -0.70558368]
 [-0.89132415 -0.11719389  0.43795758]
 [ 0.37139068 -0.74278135  0.55708601]]
[[4 2 0]
 [1 5 6]] 

[[4.00000000e+00 2.00000000e+00 2.22044605e-16]
 [1.00000000e+00 5.00000000e+00 6.00000000e+00]]
